<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/style.css">

<h3>Votre panier !</h3>
<h4>Récapitulatif de la commande</h4>
<div id="displayBasket">
	<table class="basketTable">
		<thead>
			<th>Quantité</th>
			<th>Nom</th>
			<th>Taille</th>
			<th class="desktop">Prix Unitaire</th>
			<th>Prix Total</th>
			<th>Action</th>
		</thead>
		<tfoot>
			<tr>
				<td>Prix Total</td>
				<td></td>
				<td></td>
				<td class="desktop"></td>
				<td><span id="totalPrice">00.00</span> €</td>
				<td></td>
			</tr>
		</tfoot>
		<tbody>
		</tbody>
	</table>
</div>
<form class="p-form" action="<?=$requestUrl ?>/payment" method="POST">
	<input type="hidden" name="basketItem" id="basketItem" value="">
	<input type="submit" value="Payer ma commande">
</form>