<div>
	<h3>Inscrivez-vous</h3>
	
	<form class="b-form" action="<?=$requestUrl?>/user/register" method="POST">
		<input type="text" name="firstname" placeholder="Prénom">
		<input type="text" name="lastname" placeholder="Nom">
		<input type="text" name="email" placeholder="email">
		<input type="text" name="password" placeholder="Mot de passe">
		<input type="text" name="address" placeholder="Adresse">
		<input type="text" name="city" placeholder="Ville">
		<input type="text" name="zip" placeholder="Code postal">
		<input type="submit" value="Enregister" >
	</form>
</div>